const fs = require('fs');
let content = fs.readFileSync('backend/server.js', 'utf8');
content = content.replace('ewa.location as temp_branch,\n          ewa.start_date,', 'ewa.location as temp_branch,\n          ewa.purpose,\n          ewa.remarks,\n          ewa.start_date,');
content = content.replace('const { user_id, location, start_date, end_date, status } = req.body;', 'const { user_id, location, start_date, end_date, status, purpose, remarks } = req.body;');
content = content.replace('INSERT INTO employee_work_assignment (user_id, location, start_date, end_date, status) VALUES (?, ?, ?, ?, ?)', 'INSERT INTO employee_work_assignment (user_id, location, start_date, end_date, status, purpose, remarks) VALUES (?, ?, ?, ?, ?, ?, ?)');
content = content.replace('[user_id, location, start_date, end_date || null, status || \'Active\']', '[user_id, location, start_date, end_date || null, status || \'Active\', purpose || null, remarks || null]');
content = content.replace('const { location, start_date, end_date, status } = req.body;', 'const { location, start_date, end_date, status, purpose, remarks } = req.body;');
content = content.replace('UPDATE employee_work_assignment SET location = ?, start_date = ?, end_date = ?, status = ? WHERE id = ?', 'UPDATE employee_work_assignment SET location = ?, start_date = ?, end_date = ?, status = ?, purpose = ?, remarks = ? WHERE id = ?');
content = content.replace('[location, start_date, end_date || null, status, req.params.id]', '[location, start_date, end_date || null, status, purpose || null, remarks || null, req.params.id]');
fs.writeFileSync('backend/server.js', content);
console.log('done');